# Generated by Django 4.2.1 on 2023-05-28 18:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0003_alter_blogpost_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="body",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
